#!/bin/sh /etc/rc.common

START=91

NAME=udp2raw-server
PROG=/usr/bin/udp2raw
USE_PROCD=1

start_instance() {
  local enable
  local listen_addr
  local listen_port
  local remote_addr
  local remote_port
  local password
  local raw_mode
  local cipher_mode
  local auth_mode
  local fix_gro

	config_get_bool enable $1 enable
	[ "$enable" = 1 ] || return 0

  config_get listen_addr "$1" listen_addr
  config_get listen_port "$1" listen_port
  config_get remote_addr "$1" remote_addr
  config_get remote_port "$1" remote_port
  config_get key "$1" key
  config_get raw_mode "$1" raw_mode
  config_get cipher_mode "$1" cipher_mode
  config_get auth_mode "$1" auth_mode
  config_get fix_gro "$1" fix_gro

  procd_open_instance
  procd_set_param respawn
  if [ "$fix_gro" = 1 ]; then
    procd_set_param command $PROG -s -l$listen_addr:$listen_port -r$remote_addr:$remote_port -k $key --raw-mode $raw_mode --cipher-mode $cipher_mode --auth-mode $auth_mode --fix-gro
  else
    procd_set_param command $PROG -s -l$listen_addr:$listen_port -r$remote_addr:$remote_port -k $key --raw-mode $raw_mode --cipher-mode $cipher_mode --auth-mode $auth_mode
  fi
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger $NAME
}

start_service() {
  config_load $NAME
  config_foreach start_instance udp2raw-server
}

stop_service() {
	config_load $NAME
}

reload_service() {
	stop
	start
}